### PR TITLE
Update runtime to 44

### PR DESCRIPTION
**Pull request by A6GibKm**
Continuation of https://github.com/flathub/org.gnome.font-viewer/pull/34

### CODE REVIEW

**Comment by A6GibKm** [comment]
App seems to run correctly. I haven't tested if https://github.com/flathub/org.gnome.font-viewer/pull/35/commits/f264fa2be29eba2de06edce4e0fe8e69dfe88f6a works or not.

**Comment by BrainBlasted** [comment]
We need that perm to install fonts, I'm pretty sure

**Comment by A6GibKm** [comment]
Problem is that the linter says its unnecessary and won't allow build it...

**Comment by A6GibKm** [comment]
bot, build

**Comment by hfiguiere** [comment]
bot, build

**Comment by A6GibKm** [comment]
Problem solved @BrainBlasted , but the app crashes (no logs) when installing fonts. Note that this also affects the current version.

**Pull request merged**
