### PR TITLE
Allows to install user-specific fonts

### LINKED ISSUE #11: Font installation doesn't work
Per-user font installation doesn't seem to work, it looks like
```
[Context]
filesystems=xdg-data/fonts:create;
```
is required.

`flatpak override --filesystem=xdg-data/fonts:create org.gnome.font-viewer` fixes it for me.

### PR DESCRIPTION
**Pull request by lionirdeadman**
Fixes #11

### CODE REVIEW

**Comment by Yajo** [comment]
It seems like the build was lost and I cannot test it:

<pre>➤ <font color="#005FD7">flatpak</font> <font color="#00AFFF">install</font> <font color="#00AFFF">--user</font> <font color="#00AFFF">https://dl.flathub.org/build-repo/22726/org.gnome.font-viewer.flatpakref</font>
<font color="#CC0000"><b>error: </b></font>Can&apos;t load uri https://dl.flathub.org/build-repo/22726/org.gnome.font-viewer.flatpakref: Server returned status 404: Not Found
</pre>

Any chance this can land soon? The app is pretty useless with this bug... :roll_eyes:

**Comment by lionirdeadman** [comment]
bot, build

**Comment by Yajo** [comment]
Tested, works fine!

**Review by Yajo — APPROVED** [review]

**Comment by bilelmoussaoui** [comment]
thanks

**Pull request merged**
